In [2]:
# Importing Library
import math
import pandas as pd
import numpy as np
from collections import Counter
from sklearn import *  
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

In [3]:
os.curdir
os.listdir('.')

['.git',
 'firstpython.py',
 'CreditWorthiness.xlsx',
 'games_dataset.csv',
 '.vscode',
 'My_Notebook.ipynb',
 'README.md',
 'Practice.Python.ipynb']

In [4]:
for f in os.listdir('.'):
    print(repr(f))

'.git'
'firstpython.py'
'CreditWorthiness.xlsx'
'games_dataset.csv'
'.vscode'
'My_Notebook.ipynb'
'README.md'
'Practice.Python.ipynb'

In [5]:
df = pd.read_csv("games_dataset.csv")

In [6]:
df.head()

,game_id,game_title,genre,developer,publisher,release_date,platform,price_usd,rating,number_of_players
0,1,Galaxy Conquest,Adventure,Bethesda,Ubisoft,2022-04-11,All Platforms,22.58,7.5,73344
1,2,Phantom Ops,Simulation,Activision,Bethesda,2019-04-08,Nintendo Switch,46.57,9.8,316282
2,3,Legends of Arcadia,Sports,Valve,Capcom,2021-05-10,PC,47.03,8.9,190374
3,4,Dragon Age: Resurgence,Simulation,Valve,Activision,2019-08-25,Mobile,51.87,8.4,52638
4,5,Infinite Odyssey,FPS,Square Enix,Valve,2022-05-07,Xbox Series X,56.30,6.6,83249

In [7]:
import pandas as pd
import math
import numpy as np
from collections import Counter

In [8]:
a = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 10]

In [9]:
dict(Counter(a))

{1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 1, 7: 1, 8: 1, 9: 1, 0: 1, 10: 1}

In [10]:
set(a)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [11]:
sorted(a)

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 8, 9, 10]

In [13]:
b= ["Apple", "Pineapple", "Grapes"]

[i for i in b if "APPLE" in i.upper()]

['Apple', 'Pineapple']

In [14]:
df = pd.DataFrame({"Fruits" : b})

In [15]:
df.head()

      Fruits
0      Apple
1  Pineapple
2     Grapes

In [18]:
df[df["Fruits"].str.contains( "APPLE", case = False, regex = True)]

      Fruits
0      Apple
1  Pineapple

In [19]:
df.head()

      Fruits
0      Apple
1  Pineapple
2     Grapes

In [20]:
df.drop_duplicates()

      Fruits
0      Apple
1  Pineapple
2     Grapes

In [21]:
a = ['Apple','Orange','Grapes','Pineapple']

In [26]:
b = [200, 400, 500, 600]

In [27]:
[i for i in a if "APPLE" in i.upper()]

['Apple', 'Pineapple']

In [28]:
[i for i in a if "APPLE" not in i.upper()]

['Orange', 'Grapes']

In [51]:
df1 = pd.DataFrame(zip(a, b), columns=["Fruits", "Quantity"], index = [1, 2, 3, 4])
df1

      Fruits  Quantity
1      Apple       200
2     Orange       400
3     Grapes       500
4  Pineapple       600

In [57]:
df1["Price"] = df1.apply(lambda x : 10 if x["Fruits"].upper() == "APPLE" else 20 if x["Fruits"].upper() == "ORANGE" else 30 if x["Fruits"].upper() == "GRAPES" else 40 if x["Fruits"].upper() == "PINEAPPLE" else 0, axis = 1)

In [58]:
df1

      Fruits  Quantity  Price
1      Apple       200     10
2     Orange       400     20
3     Grapes       500     30
4  Pineapple       600     40

In [60]:
df1.rename(columns={"Price" : "Cost_per_piece"},inplace = True)

In [62]:
df1

      Fruits  Quantity  Cost_per_piece
1      Apple       200              10
2     Orange       400              20
3     Grapes       500              30
4  Pineapple       600              40

In [65]:
df1["Overall_Price"] = df1.apply(lambda x : x["Quantity"] * x["Cost_per_piece"], axis = 1)

In [66]:
df1

      Fruits  Quantity  Cost_per_piece  Overall_Price
1      Apple       200              10           2000
2     Orange       400              20           8000
3     Grapes       500              30          15000
4  Pineapple       600              40          24000

In [69]:
# Sorting on basis of Overall Price

df1.sort_values(by = "Overall_Price", ascending=False, inplace=True)

In [70]:
df1

      Fruits  Quantity  Cost_per_piece  Overall_Price
4  Pineapple       600              40          24000
3     Grapes       500              30          15000
2     Orange       400              20           8000
1      Apple       200              10           2000

In [80]:
df1[df1["Overall_Price"] == max(df1["Overall_Price"])].reset_index()

   index     Fruits  Quantity  Cost_per_piece  Overall_Price
0      4  Pineapple       600              40          24000

In [83]:
elements = a.copy()
SP = [30000, 20000, 10000, 2000]
Selling = pd.DataFrame(zip(elements, SP), columns=["Fruits", "Selling_Price"])

In [85]:
Selling

      Fruits  Selling_Price
0      Apple          30000
1     Orange          20000
2     Grapes          10000
3  Pineapple           2000

In [87]:
df1

      Fruits  Quantity  Cost_per_piece  Overall_Price
4  Pineapple       600              40          24000
3     Grapes       500              30          15000
2     Orange       400              20           8000
1      Apple       200              10           2000

In [98]:
df1 = df1.merge(right = Selling, how = "left", left_on="Fruits", right_on="Fruits")

In [99]:
df1["Profit_loss_Amt"] = df1["Selling_Price"]-df1["Overall_Price"]

In [ ]:
df1

,Fruits,Quantity,Cost_per_piece,Overall_Price,Selling_Price,Profit_loss_Amt
0,Pineapple,600,40,24000,2000,-22000
1,Grapes,500,30,15000,10000,-5000
2,Orange,400,20,8000,20000,12000
3,Apple,200,10,2000,30000,28000

In [101]:
df1.rename(columns={"Overall_Price": "Cost_Price"}, inplace=True)

In [102]:
df1

,Fruits,Quantity,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt
0,Pineapple,600,40,24000,2000,-22000
1,Grapes,500,30,15000,10000,-5000
2,Orange,400,20,8000,20000,12000
3,Apple,200,10,2000,30000,28000

In [111]:
df1.drop(columns="Quantity", inplace=True)

In [112]:
df1

      Fruits  Cost_per_piece  Cost_Price  Selling_Price  Profit_loss_Amt
0  Pineapple              40       24000           2000           -22000
1     Grapes              30       15000          10000            -5000
2     Orange              20        8000          20000            12000
3      Apple              10        2000          30000            28000

In [114]:
df1["Profit&loss_pct"] = df1.apply(lambda x : str(x["Profit_loss_Amt"] * 100 /x["Cost_Price"]) + " %", axis = 1 )

In [115]:
df1

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %
2,Orange,20,8000,20000,12000,150.0 %
3,Apple,10,2000,30000,28000,1400.0 %

In [116]:
df1["Loss_or_profit"] = df1.apply(lambda x: "Loss" if x["Profit_loss_Amt"] < 0 else "Profit", axis = 1)

In [117]:
df1

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %,Loss
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,Loss
2,Orange,20,8000,20000,12000,150.0 %,Profit
3,Apple,10,2000,30000,28000,1400.0 %,Profit

In [122]:
df1["Loss_or_profit"] = df1.apply(lambda x : x["Loss_or_profit"].upper(), axis = 1)

In [123]:
df1

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %,LOSS
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,LOSS
2,Orange,20,8000,20000,12000,150.0 %,PROFIT
3,Apple,10,2000,30000,28000,1400.0 %,PROFIT

In [145]:
df1

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %,LOSS
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,LOSS
2,Orange,20,8000,20000,12000,150.0 %,PROFIT
3,Apple,10,2000,30000,28000,1400.0 %,PROFIT

In [164]:
df1.iloc[:,:]

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %,LOSS
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,LOSS
2,Orange,20,8000,20000,12000,150.0 %,PROFIT
3,Apple,10,2000,30000,28000,1400.0 %,PROFIT

In [178]:
df2 = df1.copy()

In [179]:
df2

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %,LOSS
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,LOSS
2,Orange,20,8000,20000,12000,150.0 %,PROFIT
3,Apple,10,2000,30000,28000,1400.0 %,PROFIT

In [187]:
df2["Fruits"] = df2.apply(lambda x : "Banana" if (x["Fruits"] == "Orange") & (x["Cost_Price"] > 800) else x["Fruits"]  , axis = 1)

In [188]:
df2

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
0,Pineapple,40,24000,2000,-22000,-91.66666666666667 %,LOSS
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,LOSS
2,Banana,20,8000,20000,12000,150.0 %,PROFIT
3,Apple,10,2000,30000,28000,1400.0 %,PROFIT

In [192]:
df2.iloc[1:2, :]

,Fruits,Cost_per_piece,Cost_Price,Selling_Price,Profit_loss_Amt,Profit&loss_pct,Loss_or_profit
1,Grapes,30,15000,10000,-5000,-33.333333333333336 %,LOSS

In [ ]:
# FInbonacci Serties


def fibonaci(n):
    F  = [0, 1]
    for i in range(2, n+1):
        F.append(F[i-1] + F[i-2])

    return F

fibonaci(5)

[0, 1, 1, 2, 3, 5]