In [178]:
import pandas as pd
import numpy as np
import re

# Different ways to create list

In [64]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 5, 6, 8, 9, 0]

In [22]:
a = list("Python")
a

['P', 'y', 't', 'h', 'o', 'n']

In [29]:
a[::-1]

['n', 'o', 'h', 't', 'y', 'P']

In [32]:
a.extend([1, 2])
a

['P', 'y', 't', 'h', 'o', 'n', 1, 2]

In [34]:
a.pop()
a

['P', 'y', 't', 'h', 'o', 'n']

In [37]:
a.insert(6, "a")
a

['P', 'y', 't', 'h', 'o', 'n', 'a', 'a']

In [52]:
a.pop()
a

['P', 'y', 't', 'h', 'o', 'n']

In [53]:
a.append('a')
a

['P', 'y', 't', 'h', 'o', 'n', 'a']

In [57]:
a.remove("y")
a

['t', 'h', 'o', 'n', 'a']

In [59]:
a = list("python")
a

['p', 'y', 't', 'h', 'o', 'n']

In [62]:
a.sort(reverse=True)
a

['y', 't', 'p', 'o', 'n', 'h']

In [65]:
a.count(1)

2

# Tuple

In [67]:
a = (1, 2, 3, 4)

In [71]:
sorted(a)

[1, 2, 3, 4]

In [72]:
a = ["Apple", "Grapes", "Orange", "Pineapple", "Lemonorange"]

In [80]:
b = [[10, 100], [30, 300],[ 40, 400], [50, 500], [60, 600]]

In [81]:
x = dict(zip(a, b))

In [89]:
x

{'Apple': [70, 100],
 'Grapes': [30, 300],
 'Orange': [40, 400],
 'Pineapple': [50, 500]}

In [92]:
x.get("Lemonade", "Not present")

'Not present'

In [94]:
x = set(x.keys())

In [96]:
x.add("Lemonade")

In [97]:
x

{'Apple', 'Grapes', 'Lemonade', 'Orange', 'Pineapple'}

In [100]:
y = {'Apple', 'Grapes', "Apple shake"}
y

{'Apple', 'Apple shake', 'Grapes'}

In [103]:
x.difference(y)

{'Lemonade', 'Orange', 'Pineapple'}

In [104]:
y.difference(x)

{'Apple shake'}

In [105]:
print(f"sdcfsdchubsdchbsdchsbdchu{x}")

sdcfsdchubsdchbsdchsbdchu{'Apple', 'Grapes', 'Orange', 'Lemonade', 'Pineapple'}

In [106]:
# Assigning Grade to a drink
x = x.union(y)

In [119]:
x = list(x)
x

['Apple', 'Grapes', 'Orange', 'Apple shake', 'Pineapple', 'Lemonade']

In [120]:
# Retyurn Matching keyword
[i for i in x if "APPLE" in i.upper()]

['Apple', 'Apple shake', 'Pineapple']

In [131]:
list(map(lambda i : i if "APPLE" in i.upper() else None, x))

['Apple', None, None, 'Apple shake', 'Pineapple', None]

In [164]:
a = ["+910000", "941", "+91656565"]
a

['+910000', '941', '+91656565']

In [158]:
list(filter(lambda x : "+91" in x, a))

['+910000', '+91656565']

In [160]:
[i.replace("+91", "") if "+91" in i else i for i in a]

['0000', '941', '656565']

In [170]:
df = pd.DataFrame(a,columns = ["Ph_no"])

In [171]:
df.head()

       Ph_no
0    +910000
1        941
2  +91656565

In [175]:
df["Cleaned_ph"] = df.apply(lambda x : x["Ph_no"].replace("+91", "") if "+91" in x["Ph_no"] else x["Ph_no"], axis = 1)
df

       Ph_no Cleaned_ph
0    +910000       0000
1        941        941
2  +91656565     656565

In [176]:
x = ["+919989898989888debasa", "+91hdsbhcbhcbhcb5757575hj", "sajdbsajhdbsadbd", "18387484", "1212121dfgdffg"]

In [179]:
[re.findall(r"\d+",i) for i in x]

[['919989898989888'], ['91', '5757575'], [], ['18387484'], ['1212121']]

In [180]:
[re.findall(r"[a-z-A-Z]+",i) for i in x]

[['debasa'], ['hdsbhcbhcbhcb', 'hj'], ['sajdbsajhdbsadbd'], [], ['dfgdffg']]

In [183]:
dfx = pd.DataFrame(x, columns =["TEXT"])
dfx

                        TEXT
0     +919989898989888debasa
1  +91hdsbhcbhcbhcb5757575hj
2           sajdbsajhdbsadbd
3                   18387484
4             1212121dfgdffg

Extract Numbers

In [191]:
dfx["TEXT"].apply(lambda x : re.findall(r'\d+', x))

0    [919989898989888]
1        [91, 5757575]
2                   []
3           [18387484]
4            [1212121]
Name: TEXT, dtype: object

EXTRACT TEXT

In [193]:
dfx["TEXT"].apply(lambda x : re.findall(r'[a-z-A-Z]+', x))

0               [debasa]
1    [hdsbhcbhcbhcb, hj]
2     [sajdbsajhdbsadbd]
3                     []
4              [dfgdffg]
Name: TEXT, dtype: object

In [194]:
# aGAIN FOR PRACTICE ------ dIFIT eXTRARCTRION

In [195]:
import re

In [196]:
x

['+919989898989888debasa',
 '+91hdsbhcbhcbhcb5757575hj',
 'sajdbsajhdbsadbd',
 '18387484',
 '1212121dfgdffg']

In [198]:
# extract numbers
[re.findall(r"\d+",i) for i in x ]

[['919989898989888'], ['91', '5757575'], [], ['18387484'], ['1212121']]

In [199]:
# extract alphabet
[re.findall(r'[A-Z-a-z]+', i) for i in x]

[['debasa'], ['hdsbhcbhcbhcb', 'hj'], ['sajdbsajhdbsadbd'], [], ['dfgdffg']]

In [200]:
dfx

                        TEXT
0     +919989898989888debasa
1  +91hdsbhcbhcbhcb5757575hj
2           sajdbsajhdbsadbd
3                   18387484
4             1212121dfgdffg

In [202]:
dfx["TEXT"].apply(lambda x : re.findall(r'\d+', x))

0    [919989898989888]
1        [91, 5757575]
2                   []
3           [18387484]
4            [1212121]
Name: TEXT, dtype: object

In [203]:
dfx["TEXT"].apply(lambda x : re.findall(r"[A-Z-a-z]+", x))

0               [debasa]
1    [hdsbhcbhcbhcb, hj]
2     [sajdbsajhdbsadbd]
3                     []
4              [dfgdffg]
Name: TEXT, dtype: object

In [209]:
x = pd.DataFrame(zip([1, 2, 3, 4, 5, 1], [10, 20, 30, 40, 50, 200]), columns=["id", "Amount"])

In [210]:
x

   id  Amount
0   1      10
1   2      20
2   3      30
3   4      40
4   5      50
5   1     200

In [221]:
x1 = x.groupby(by = "id").agg(Amount = ("Amount", "sum"), count_id = ("id", "count"), distinct_count = ("id", "nunique")).reset_index()

In [222]:
x1

   id  Amount  count_id  distinct_count
0   1     210         2               1
1   2      20         1               1
2   3      30         1               1
3   4      40         1               1
4   5      50         1               1

In [228]:
x1 = x.merge(right = x1, left_on="id", right_on="id", how = "left")

KeyError: 'id'

In [229]:
x1.rename(columns={"id": "cust_id"}, inplace = True)

In [230]:
x1

   cust_id  Amount  count_id  distinct_count
0        1     210         2               1
1        2      20         1               1
2        3      30         1               1
3        4      40         1               1
4        5      50         1               1

In [231]:
x1.loc[x1["cust_id"] == 5, "cust_id"] = 6

In [232]:
x1

   cust_id  Amount  count_id  distinct_count
0        1     210         2               1
1        2      20         1               1
2        3      30         1               1
3        4      40         1               1
4        6      50         1               1

In [234]:
x1.replace(1, 0, inplace=True)

In [235]:
x1

   cust_id  Amount  count_id  distinct_count
0        0     210         2               0
1        2      20         0               0
2        3      30         0               0
3        4      40         0               0
4        6      50         0               0

In [239]:
x1["count_id"].nunique()

2

In [240]:
x1.dropna(inplace = True)

In [241]:
x1

   cust_id  Amount  count_id  distinct_count
0        0     210         2               0
1        2      20         0               0
2        3      30         0               0
3        4      40         0               0
4        6      50         0               0

In [243]:
x1 = x1[x1["Amount"] > 50]

In [244]:
x1

   cust_id  Amount  count_id  distinct_count
0        0     210         2               0